"""In-app notifications + candidate outreach (platform Phase 6).

Notifications are tenant-scoped and generated by platform events (see
`record_notification`, called from the candidates router when a high-risk CV is
promoted). Outreach logs a recruiter's touches on a candidate and can generate a
first-draft message.
"""
from __future__ import annotations

import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from auth import get_current_org_optional, get_current_user
from db import get_db
from db_models import Candidate, Notification, OutreachMessage
from outreach import draft_outreach
from routers._common import tenant_scope

router = APIRouter(tags=["notifications"])


def record_notification(
    db: Session,
    *,
    user_id: str,
    org_id: Optional[str],
    type: str,
    title: str,
    body: Optional[str] = None,
    candidate_id=None,
) -> None:
    """Persist a notification. Best-effort: callers should not let a
    notification failure break the primary action, so this commits on its own."""
    db.add(
        Notification(
            user_id=user_id,
            org_id=org_id,
            type=type,
            title=title,
            body=body,
            candidate_id=candidate_id,
        )
    )
    db.commit()


# ── Schemas ──────────────────────────────────────────────────────────────────

class NotificationOut(BaseModel):
    id: str
    type: str
    title: str
    body: Optional[str]
    candidate_id: Optional[str]
    read: bool
    created_at: str


class NotificationListOut(BaseModel):
    notifications: list[NotificationOut]
    unread_count: int


class UnreadCountOut(BaseModel):
    count: int


class OutreachCreate(BaseModel):
    body: str = Field(min_length=1)
    channel: str = Field(default="note", max_length=16)
    subject: Optional[str] = Field(default=None, max_length=256)


class OutreachOut(BaseModel):
    id: str
    channel: str
    subject: Optional[str]
    body: str
    created_at: str


class OutreachDraftOut(BaseModel):
    subject: str
    body: str


def _require_db(db: Optional[Session]) -> Session:
    if db is None:
        raise HTTPException(status_code=503, detail="Database is not configured.")
    return db


def _notif_out(n: Notification) -> NotificationOut:
    return NotificationOut(
        id=str(n.id),
        type=n.type,
        title=n.title,
        body=n.body,
        candidate_id=str(n.candidate_id) if n.candidate_id else None,
        read=bool(n.read),
        created_at=n.created_at.isoformat(),
    )


# ── Notifications ────────────────────────────────────────────────────────────

@router.get("/notifications", response_model=NotificationListOut)
def list_notifications(
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> NotificationListOut:
    db = _require_db(db)
    q = tenant_scope(db.query(Notification), Notification, current_user, current_org)
    # Unread first, then newest. The display list is capped at 50, but the
    # unread badge must reflect the TRUE unread total (Codex P-round: counting
    # unread within the capped page under-reports once >50 unread exist).
    rows = q.order_by(Notification.read.asc(), Notification.created_at.desc()).limit(
        50
    ).all()
    unread = (
        tenant_scope(db.query(Notification), Notification, current_user, current_org)
        .filter(Notification.read == 0)
        .count()
    )
    return NotificationListOut(
        notifications=[_notif_out(n) for n in rows], unread_count=unread
    )


@router.get("/notifications/unread-count", response_model=UnreadCountOut)
def unread_count(
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> UnreadCountOut:
    db = _require_db(db)
    n = (
        tenant_scope(db.query(Notification), Notification, current_user, current_org)
        .filter(Notification.read == 0)
        .count()
    )
    return UnreadCountOut(count=n)


@router.post("/notifications/{notification_id}/read", response_model=NotificationOut)
def mark_read(
    notification_id: uuid.UUID,
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> NotificationOut:
    db = _require_db(db)
    n = tenant_scope(
        db.query(Notification).filter(Notification.id == notification_id),
        Notification,
        current_user,
        current_org,
    ).first()
    if n is None:
        raise HTTPException(status_code=404, detail="Notification not found.")
    n.read = 1
    db.commit()
    db.refresh(n)
    return _notif_out(n)


@router.post("/notifications/read-all", response_model=UnreadCountOut)
def mark_all_read(
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> UnreadCountOut:
    db = _require_db(db)
    tenant_scope(
        db.query(Notification), Notification, current_user, current_org
    ).filter(Notification.read == 0).update(
        {Notification.read: 1}, synchronize_session=False
    )
    db.commit()
    return UnreadCountOut(count=0)


# ── Outreach ─────────────────────────────────────────────────────────────────

def _load_candidate(db: Session, candidate_id, user: str, org: Optional[str]) -> Candidate:
    c = tenant_scope(
        db.query(Candidate).filter(Candidate.id == candidate_id),
        Candidate,
        user,
        org,
    ).first()
    if c is None:
        raise HTTPException(status_code=404, detail="Candidate not found.")
    return c


@router.get("/candidates/{candidate_id}/outreach", response_model=list[OutreachOut])
def list_outreach(
    candidate_id: uuid.UUID,
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> list[OutreachOut]:
    db = _require_db(db)
    _load_candidate(db, candidate_id, current_user, current_org)
    rows = (
        db.query(OutreachMessage)
        .filter(OutreachMessage.candidate_id == candidate_id)
        .order_by(OutreachMessage.created_at.desc())
        .all()
    )
    return [
        OutreachOut(
            id=str(m.id),
            channel=m.channel,
            subject=m.subject,
            body=m.body,
            created_at=m.created_at.isoformat(),
        )
        for m in rows
    ]


@router.post(
    "/candidates/{candidate_id}/outreach", response_model=OutreachOut, status_code=201
)
def log_outreach(
    candidate_id: uuid.UUID,
    body: OutreachCreate,
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> OutreachOut:
    db = _require_db(db)
    _load_candidate(db, candidate_id, current_user, current_org)
    msg = OutreachMessage(
        user_id=current_user,
        org_id=current_org,
        candidate_id=candidate_id,
        channel=body.channel,
        subject=body.subject,
        body=body.body,
    )
    db.add(msg)
    db.commit()
    db.refresh(msg)
    return OutreachOut(
        id=str(msg.id),
        channel=msg.channel,
        subject=msg.subject,
        body=msg.body,
        created_at=msg.created_at.isoformat(),
    )


@router.post(
    "/candidates/{candidate_id}/outreach/draft", response_model=OutreachDraftOut
)
def draft_candidate_outreach(
    candidate_id: uuid.UUID,
    db: Session | None = Depends(get_db),
    current_user: str = Depends(get_current_user),
    current_org: str | None = Depends(get_current_org_optional),
) -> OutreachDraftOut:
    db = _require_db(db)
    cand = _load_candidate(db, candidate_id, current_user, current_org)
    draft = draft_outreach(full_name=cand.full_name, headline=cand.headline)
    return OutreachDraftOut(subject=draft.subject, body=draft.body)
